(define (make-account balance password)
 	(define (withdraw amount)
	 	(if (>= balance amount)
		    (begin (set! balance (- balance amount))
		           balance)
		    "Insufficient funds"))
	(define (deposit amount)
	 	(begin (set! balance (+ balance amount))
		       balance))
	(define (dispatch pass m)
	        (if (not (eq? pass password))
		    "Incorrect password"
		    (cond ((eq? m 'withdraw) withdraw)
		          ((eq? m 'deposit) deposit)
			  (else (error "Unknown request -- MAKE-ACCOUNT" m)))))
	dispatch)

