(load "3.3-make-account.scm")

(define (call-the-cops)
 	"Call the cops")

(define (new-make-account balance password)
 	(define (withdraw amount)
	 	(if (>= balance amount)
		    (begin (set! balance (- balance amount))
		           balance)
		    "Insufficient funds"))
	(define (deposit amount)
	 	(set! balance (+ balance amount)))
	(define (dispatch pass m)
	 	(let ((count 0))
	        (if (not (eq? pass password))
		    (if (> 7 count)
		    	(begin (set! count (+ count 1)) (display "Incorrect password"))
			(call-the-cops))
		    ((begin (set! count 0)
			    (cond ((eq? m 'withdraw) withdraw)
				  ((eq? m 'deposit) deposit)
				  (else (error "Unknown request -- MAKE-ACCOUNT" m))))))))
	dispatch)
