(load "1.37-cont-frac.scm")
(define (tan-cf x k)
 	;(define (pow a n)
	; 	(cond ((= n 0) 1)
	;	      ((even? n) (square (pow a (/ n 2))))
	;	      (else (* (pow a (- n 1)) a))))
	(define (square x) (* x x))
 	(cont-frac (lambda (i) (- (square x)))
	 	   (lambda (i) (- (* i 2) 1))
		   k))
